# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Using CodeCov: https://github.com/codecov/example-r

language: R
r: bioc-devel
warnings_are_errors: true
sudo: required
cache: packages

apt_packages:
 - libnetcdf-dev
 - netcdf-bin

after_success:
 - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change